esphome:
  name: labor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "RoboFish"
  password: "vhr0b0134js"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Labor Fallback Hotspot"
    password: "8pr6nUuzOwJc"

captive_portal: 

web_server:
  port: 80
  version: 3

# 🌱 Kapazitiver Sensor auf GPIO34
sensor:
  - platform: adc
    pin: GPIO32
    name: "Bodenfeuchtigkeit 1"
    id: feuchte_raw_32
    update_interval: 1s
    attenuation: 12db  # Für ESP32 wichtig bei 0–3.3V Bereich
    filters:
      - multiply: 4096  # Konvertiert von 0.0–1.0 in 0–4095 Bereich
  - platform: adc
    pin: GPIO33
    name: "Bodenfeuchtigkeit 2"
    id: feuchte_raw_33
    update_interval: 1s
    attenuation: 12db  # Für ESP32 wichtig bei 0–3.3V Bereich
    filters:
      - multiply: 4096  # Konvertiert von 0.0–1.0 in 0–4095 Bereich
  - platform: adc
    pin: GPIO34
    name: "Bodenfeuchtigkeit 3"
    id: feuchte_raw_34
    update_interval: 1s
    attenuation: 12db  # Für ESP32 wichtig bei 0–3.3V Bereich
    filters:
      - multiply: 4096  # Konvertiert von 0.0–1.0 in 0–4095 Bereich
  - platform: adc
    pin: GPIO35
    name: "Bodenfeuchtigkeit 4"
    id: feuchte_raw_35
    update_interval: 1s
    attenuation: 12db  # Für ESP32 wichtig bei 0–3.3V Bereich
    filters:
      - multiply: 4096  # Konvertiert von 0.0–1.0 in 0–4095 Bereich
number:
  - platform: template
    name: "Trocken-Schwellenwert-1"
    id: trocken_schwelle_1
    optimistic: true
    min_value: 100
    max_value: 10000
    step: 50
    initial_value: 2000
    restore_value: true
    mode: slider
  - platform: template
    name: "Trocken-Schwellenwert-2"
    id: trocken_schwelle_2
    optimistic: true
    min_value: 100
    max_value: 10000
    step: 50
    initial_value: 2000
    restore_value: true
    mode: slider
  - platform: template
    name: "Trocken-Schwellenwert-3"
    id: trocken_schwelle_3
    optimistic: true
    min_value: 100
    max_value: 10000
    step: 50
    initial_value: 2000
    restore_value: true
    mode: slider
  - platform: template
    name: "Trocken-Schwellenwert-4"
    id: trocken_schwelle_4
    optimistic: true
    min_value: 100
    max_value: 10000
    step: 50
    initial_value: 2000
    restore_value: true
    mode: slider
# ⚡ Relais an GPIO4 (D2 bei vielen Boards)
switch:
  - platform: gpio
    pin: GPIO5
    id: relais5
    name: "Pumpe 1"
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO18
    id: relais18
    name: "Pumpe 2"
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO19
    id: relais19
    name: "Pumpe 3"
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO21
    id: relais21
    name: "Pumpe 4"
    restore_mode: ALWAYS_OFF
  
# 💡 Logik: Vergleicht Sensorwert mit Benutzergrenze
binary_sensor:
  - platform: template
    name: "Zu Trocken laut Benutzergrenze"
    lambda: |-
      if (id(feuchte_raw_32).state < id(trocken_schwelle_1).state) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: relais5
    on_release:
      then:
        - switch.turn_off: relais5
  - platform: template
    name: "Zu Trocken laut Benutzergrenze"
    lambda: |-
      if (id(feuchte_raw_33).state < id(trocken_schwelle_2).state) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: relais18
    on_release:
      then:
        - switch.turn_off: relais18
  - platform: template
    name: "Zu Trocken laut Benutzergrenze"
    lambda: |-
      if (id(feuchte_raw_34).state < id(trocken_schwelle_3).state) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: relais21
    on_release:
      then:
        - switch.turn_off: relais21
  - platform: template
    name: "Zu Trocken laut Benutzergrenze"
    lambda: |-
      if (id(feuchte_raw_35).state < id(trocken_schwelle_4).state) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: relais19
    on_release:
      then:
        - switch.turn_off: relais19
    